# Generated by Django 5.1.3 on 2025-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('face_image', models.ImageField(upload_to='faces/')),
            ],
        ),
    ]
