# Generated by Django 5.1.3 on 2025-05-28 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facereco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='register',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='semester',
            field=models.CharField(max_length=10),
        ),
    ]
