# Generated by Django 6.0.5 on 2026-08-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facereco', '0004_subject_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
