# Generated by Django 6.0.5 on 2026-08-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facereco', '0005_register_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='face_encoding',
        ),
    ]
