# Generated by Django 6.0.5 on 2026-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facereco', '0008_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
