# Generated by Django 6.0.5 on 2026-10-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facereco", "0009_teacherprofile_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegeHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National Holiday"),
                            ("STATE", "State Holiday"),
                            ("RESTRICTED", "Restricted Holiday"),
                            ("COLLEGE", "College Holiday"),
                            ("VACATION", "Vacation"),
                            ("EXAM", "Examination"),
                        ],
                        max_length=15,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("applies_to_all", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubjectScheduleRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theory_classes_per_week",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "theory_duration_minutes",
                    models.PositiveSmallIntegerField(default=50),
                ),
                ("lab_classes_per_week", models.PositiveSmallIntegerField(default=0)),
                (
                    "lab_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=120,
                        help_text="Duration of each lab session in minutes.",
                    ),
                ),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_requirement",
                        to="facereco.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_requirements",
                        to="facereco.teacherprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimetableConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                ("branch", models.CharField(max_length=50)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("1", "1st Semester"),
                            ("2", "2nd Semester"),
                            ("3", "3rd Semester"),
                            ("4", "4th Semester"),
                            ("5", "5th Semester"),
                            ("6", "6th Semester"),
                            ("7", "7th Semester"),
                            ("8", "8th Semester"),
                        ],
                        max_length=2,
                    ),
                ),
                ("college_start", models.TimeField()),
                ("college_end", models.TimeField()),
                ("lunch_start", models.TimeField()),
                ("lunch_end", models.TimeField()),
                ("working_days", models.PositiveSmallIntegerField(default=6)),
                (
                    "default_theory_duration",
                    models.PositiveSmallIntegerField(default=50),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("academic_year", "branch", "semester"),
                        name="unique_timetable_configuration",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimetableSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[("THEORY", "Theory"), ("LAB", "Practical / Lab")],
                        max_length=10,
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="facereco.timetableconfiguration",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facereco.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facereco.teacherprofile",
                    ),
                ),
            ],
        ),
    ]
