# Generated by Django 6.0.5 on 2026-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facereco", "0010_collegeholiday_subjectschedulerequirement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableconfiguration",
            name="lab_rooms",
            field=models.CharField(
                default="Lab 1,Lab 2",
                help_text="Comma-separated practical lab room numbers",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="timetableconfiguration",
            name="theory_rooms",
            field=models.CharField(
                default="204,205,208",
                help_text="Comma-separated theory classroom numbers",
                max_length=255,
            ),
        ),
    ]
